server:
  port: 8080
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: path/to.p12
#    key-store-password:

spring:
#  datasource:
#    url: jdbc:h2:mem:test
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false        # SQL to console, bypassing logger
        format_sql: true       # SQL to log AND console

  jackson:
    deserialization:
      fail_on_unknown_properties: true

logging:
  level:
    de.igorakkerman.demo: INFO
