server:
  port: 8080
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: path/to.p12
#    key-store-password:

spring:
#  datasource:
#    url: jdbc:h2:mem:test
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  jackson:
    deserialization:
      fail_on_unknown_properties: true

logging:
  level:

    de.igorakkerman.demo: DEBUG

#    org.hibernate: DEBUG
    org.hibernate.type: TRACE
#    org.hibernate.type: TRACE
#    org.hibernate.internal.util.EntityPrinter: DEBUG
#    org.hibernate.jpa.internal.util.LogHelper: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.hbm2ddl: DEBUG

#    org.springframework.test.context: INFO
#    org.springframework.transaction: TRACE
#    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: DEBUG
#    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

#    org.zalando.logbook: TRACE
