spring:
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
#      jdbc-url: jdbc:postgresql://postgres:5432/deviceconfig
      connectionTimeout: 3000
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        show_sql: false        # SQL to console, bypassing logger
        format_sql: true       # SQL to log AND console
    hibernate:
      ddl-auto: update

  jackson:
    deserialization:
      fail_on_unknown_properties: true

springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    disable-swagger-default-url: true
    url: /api/openapi.yaml
    default-model-expand-depth: 10
    default-models-expand-depth: -1

logging:
  level:
    de.igorakkerman.demo: INFO
