name: build and deploy

on:
  [push]
#    branches: [ $default-branch ]
#  pull_request:
#    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: JDK 17 (Eclipse Temurin) setup
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Gradle wrapper preparation
        run: |
          chmod +x gradlew
      - name: Gradle Kotlin build
        run: |
           ./gradlew build
      - name: Gradle container image build
        run: |
           ./gradlew jibDockerBuild
